format = """
$fill
 $os$all
    ${custom.TZdate}$time
$fill
$character
"""

[os]
disabled = false

[fill]
symbol = "."

[time]
disabled = false
style = "bold bright-black"
format = "[$time]($style)"

[hostname]
ssh_symbol = "ğŸŒ "

[git_branch]
symbol = "ğŸšƒ "

[line_break]
disabled = true

[custom.TZdate]
command = "date +'%a %d %b'"
when = true
