format = """
$os$username$hostname$all
- $time

$character
"""

[hostname]
ssh_symbol = "ğŸŒ "

[git_branch]
symbol = "ğŸšƒ "

[line_break]
disabled = true

[directory]
truncation_length = 0
style = "bold #3B00A8 bg:#DBC7FF"

[battery]
disabled = true

[time]
disabled = false
style = "italic"
format = "[$time]($style)"

# disable due to slow performence
#[custom.TZdate]
#style = "italic"
#command = "date +'%a %d %b'"
#when = true

[character]
success_symbol = "ğŸ‘‰ "
error_symbol = "ğŸ‘ "
