format = """
$os$username$hostname$directory$git_branch${custom.repo}$git_status$git_state$docker_context$package$nodejs$python$rust$golang$java$kotlin$php$ruby$swift$terraform$aws$gcloud$azure$kubernetes$helm$conda$bun$deno$elixir$elm$erlang$haskell$julia$lua$nim$ocaml$perl$pulumi$rlang$scala$zig$nix_shell$memory_usage$env_var$cmd_duration$jobs$sudo$shell
- $time

$character
"""

[hostname]
ssh_symbol = "ğŸŒ "

[git_branch]
symbol = "ğŸšƒ "

[line_break]
disabled = true

[directory]
truncation_length = 0
style = "bold #3B00A8 bg:#DBC7FF"

[battery]
disabled = true

[time]
disabled = false
style = "italic"
format = "[$time]($style)"

# disable due to slow performence
#[custom.TZdate]
#style = "italic"
#command = "date +'%a %d %b'"
#when = true

[custom.repo]
command = "git remote get-url origin 2>/dev/null | awk -F'[:/]' '{gsub(/\\.git$/,\"\"); print $(NF-1)\"/\"$NF}'"
when = "git rev-parse --is-inside-work-tree 2>/dev/null"
format = "from [$output]($style) "
style = "bold purple"

[character]
success_symbol = "ğŸ‘‰ "
error_symbol = "ğŸ‘ "
